### ISSUE TITLE
Extract coordinates of the each boundary box 

### ISSUE THREAD

**Issue by alfredeep** [xdever/RFCN-tensorflow#11]
Hello,
Can I retrieve the coordinates (x, y, width, height) of the boundary box for each object and save them in text file? if yes so how can I extract them.

Thank you

**Comment by obendidi** [comment]
in line 91 in the [test.py](https://github.com/xdever/RFCN-tensorflow/blob/master/test.py),you have :
"rBoxes" : cordinate of the box 
"rScores" : confidence of the box
"rClasses" : class of the box"

**Comment by RobertCsordas** [comment]
Thank you for your help, bendidi!

**Comment by alfredeep** [comment]
Thank you very much
