### ISSUE TITLE
anchors .. how to choose anchors for custom dataset ?

### ISSUE THREAD

**Issue by obendidi** [xdever/RFCN-tensorflow#14]
Hello, 
I've trained the RFCN on my own dataset (4K images :100: )  to detect some custom object , the results are not half bad , but I need more precision , so I was wondering if the selection of anchors plays an important role in the final precision , and if so what is the method to choose anchors ?

Thank you !

**Comment by RobertCsordas** [comment]
Hi,

They help a few percent, but it not like doubling your score (alhough your data may significantly differ from mine, in which case I would help more I guess).

In line 33 of BoxEngine/BoxNetwork.py you can pass them to constructor of RPN as anchors= [[h1,w1],[h2,w2],...].

You can use k-means clustering to find good anchor candidates for your dataset.

Happy hacking :)!

**Comment by obendidi** [comment]
Great ! thanks :+1:

**Comment by ApoorvaOjha** [comment]
> Hello,
> I've trained the RFCN on my own dataset (4K images 💯 ) to detect some custom object , the results are not half bad , but I need more precision , so I was wondering if the selection of anchors plays an important role in the final precision , and if so what is the method to choose anchors ?
> 
> Thank you !

Hey can you please explain steps to train custom dataset? thank you in advance.
