### ISSUE TITLE
It should be USE_OLD_EABI=1, instead of USE_OLD_EABI=0 

### ISSUE THREAD

**Issue by kiinghom** [xdever/RFCN-tensorflow#15]
you can find in the Makefile: 
ifeq (${USE_OLD_EABI}, 1)
	EABIFLAGS=-D_GLIBCXX_USE_CXX11_ABI=0

**Comment by RobertCsordas** [comment]
I think it shouldn't. Should be 1 when TF is compiled with GCC version 5 or earlier. For ver >=6, USE_OLD_EABI should be 0.
