### ISSUE TITLE
Unsuccessful TensorSliceReader constructor: Failed to find any matching files for ./inception_resnet_v2_2016_08_30.ckpt

### ISSUE THREAD

**Issue by twinsyssy1018** [xdever/RFCN-tensorflow#25]

**Comment by RobertCsordas** [comment]
I don't provide that file. I provide a trained network file which is not equivalent to this. It is supposed to download it from the internet if missing. See Utils/Model.py. I don't know why the automatic download is not working for you. Is there any other error message displayed?

**Comment by twinsyssy1018** [comment]
@xdever  it is written in main.py  : 
131 with tf.Session(config=tf.ConfigProto(intra_op_parallelism_threads=8)) as sess:
132         if not loadCheckpoint(sess, opt.name+"/save/", opt.resume):
133                 print("Loading GoogleNet")
134                 net.importWeights(sess, "./inception_resnet_v2_2016_08_30.ckpt")
135                 #net.importWeights(sess, "initialWeights/", permutateRgb=False)
136                 print("Done.")
