### ISSUE TITLE
how can we adapt nonlocal vars to python 2.7?

### ISSUE THREAD

**Issue by marmus12** [xdever/RFCN-tensorflow#3]
in InceptionResnetV2.py, there are two nonlocal variables called trainBnEntered and currBlock. In python 2.7, the keyword nonlocal is not defined. when I comment them out it seems to get problematic to finetune earlier layers. so how should we fix the code to make it suitable to python2.7?

**Comment by RobertCsordas** [comment]
I never used python 2.7, but I think the global keyword should be used instead.

**Comment by marmus12** [comment]
I declared these variables as global in the functions that assign value to them and deleted the nonlocal statements. now I can train starting from any scope I want. so thank you for your help, your code is awesome!
