### ISSUE TITLE
Error make

### ISSUE THREAD

**Issue by ghali007** [xdever/RFCN-tensorflow#46]
When I run make, I obtained this error

make -C BoxEngine/ROIPooling all
make[1]: Entering directory '/content/drive/My Drive/RFCN-tensorflow/BoxEngine/ROIPooling'
g++  -std=c++11 -O2 -D GOOGLE_CUDA=1 -c -o roi_pooling.o roi_pooling.cc -I /usr/local/lib/python3.6/dist-packages/tensorflow_core/include -I /usr/local/lib/python3.6/dist-packages/tensorflow_core/include/external/nsync/public -I /usr/local/cuda/include -fPIC -O2
g++ -std=c++11 -O2 -D GOOGLE_CUDA=1 -c -o roi_pooling_grad.o roi_pooling_grad.cc -I /usr/local/lib/python3.6/dist-packages/tensorflow_core/include -I /usr/local/lib/python3.6/dist-packages/tensorflow_core/include/external/nsync/public -I /usr/local/cuda/include -fPIC -O2
/usr/local/cuda/bin/nvcc -std=c++11 -c -o roi_pooling.cu.o roi_pooling.cu.cc -I /usr/local/lib/python3.6/dist-packages/tensorflow_core/include -I /usr/local/lib/python3.6/dist-packages/tensorflow_core/include/external/nsync/public -I /usr/local/cuda/include -D GOOGLE_CUDA=1 -x cu -Xcompiler -fPIC -arch=sm_37 -use_fast_math
/usr/local/cuda/bin/nvcc -std=c++11 -c -o roi_pooling_grad.cu.o roi_pooling_grad.cu.cc -I /usr/local/lib/python3.6/dist-packages/tensorflow_core/include -I /usr/local/lib/python3.6/dist-packages/tensorflow_core/include/external/nsync/public -I /usr/local/cuda/include -D GOOGLE_CUDA=1 -x cu -Xcompiler -fPIC -arch=sm_37 -use_fast_math
g++  -std=c++11 -O2 -D GOOGLE_CUDA=1 -shared -o roi_pooling.so roi_pooling.o roi_pooling_grad.o roi_pooling.cu.o roi_pooling_grad.cu.o -I /usr/local/lib/python3.6/dist-packages/tensorflow_core/include -I /usr/local/lib/python3.6/dist-packages/tensorflow_core/include/external/nsync/public -I /usr/local/cuda/include -fPIC -O2 -L /usr/local/cuda/targets/x86_64-linux/lib -L /usr/local/cuda/lib64/ -L /usr/local/cuda/extras/CUPTI/lib64/ -lcudart -L /usr/local/lib/python3.6/dist-packages/tensorflow_core -ltensorflow_framework
/usr/bin/ld: cannot find -ltensorflow_framework
collect2: error: ld returned 1 exit status
Makefile:32: recipe for target 'roi_pooling.so' failed
make[1]: *** [roi_pooling.so] Error 1
make[1]: Leaving directory '/content/drive/My Drive/RFCN-tensorflow/BoxEngine/ROIPooling'
Makefile:2: recipe for target 'all' failed
make: *** [all] Error 2

**Comment by arthur9812** [comment]
same error

**Comment by kurtpumares** [comment]
If using TF 1.x, [this](https://github.com/bgshih/aster/issues/56#issuecomment-501973315) comment from another issue might help.
If using TF 2.x, check the Makefile in `BoxEngine/ROIPooling/` and replace `-ltensorflow_framework` to `-fPIC`.
