### ISSUE TITLE
Error while running demo file -> KeyError: 'Repeat_1'

### ISSUE THREAD

**Issue by ananddb90** [xdever/RFCN-tensorflow#6]
Hi @xdever , 
while running demo test.py, I am getting below error. I am not able to understand what exactly is the problem.

anand@aicenter001:~/Desktop/anand/RFCN-tensorflow$ ./test.py -n pretrained/export/model.data-00000-of-00001 -i PEDS-CityTrafficB.jpg -o PEDS-CityTrafficB1.jpg

Training network from end
Traceback (most recent call last):
  File "./test.py", line 51, in <module>
    net = BoxInceptionResnet(image, len(categories), name="boxnet")
  File "/home/anand/Desktop/anand/RFCN-tensorflow/BoxInceptionResnet.py", line 43, in __init__
    scale_16 = self.googleNet.getOutput("Repeat_1")[:,1:-1,1:-1,:]
  File "/home/anand/Desktop/anand/RFCN-tensorflow/InceptionResnetV2.py", line 277, in getOutput
    return self.endPoints[name]
KeyError: 'Repeat_1'

Could you please help me to know the possible reason and how can I fix this. 

Thank you.

**Comment by RobertCsordas** [comment]
Dear @ananddb90,
It's probably because you are using python2. I just made a modification which should make code python2 compatible. Please check if it fixes the problem.

**Comment by Jamescallow** [comment]
There is no 'nonlocal' in python2,you should update python2 to python3 or write a function  which realize the 'nonlocal' by yourself

**Comment by RobertCsordas** [comment]
I already removed the nonlocal keyword, tried to train it in python2, and it works fine.

**Comment by Jamescallow** [comment]
@xdever OK,thank you for telling me.

**Comment by ananddb90** [comment]
@xdever thank you for your help
