### ISSUE TITLE
Runtime TypeError in CPU version

### ISSUE THREAD

**Issue by sevaxyz** [xdever/RFCN-tensorflow#8]
Greetings,

Thank you for the code.

I am trying to compile a CPU-only version of the code and launch the `./test.py` script. I removed the nvcc lines in BoxEngine/ROIPooling/Makefile and commented the GPU-related lines in the source code. The .so is compiled with no issues, but running the `./test.py` yields the following error:

```
~/RFCN-tensorflow$ ./test.py -n export/model -i ./test_imgs/1.jpg -o o.jpg
Training network from end
('Anchors: ', [[64, 64], [90, 45], [45, 90], [128, 128], [181, 90], [90, 181], [256, 256], [362, 181], [181, 362], [512, 512], [724, 362], [362, 724]])
Traceback (most recent call last):
  File "./test.py", line 51, in <module>
    net = BoxInceptionResnet(image, len(categories), name="boxnet")
  File "/home/username/RFCN-tensorflow/BoxInceptionResnet.py", line 58, in __init__
    BoxNetwork.__init__(self, nCategories, rpnInput, 16, [32,32], featureInput, 16, [32,32], weightDecay=weightDecay, hardMining=hardMining)
  File "/home/username/RFCN-tensorflow/BoxEngine/BoxNetwork.py", line 36, in __init__
    self.proposals, self.proposalScores = self.rpn.getPositiveOutputs(maxOutSize=300)
  File "/home/username/RFCN-tensorflow/BoxEngine/RPN.py", line 230, in getPositiveOutputs
    boxes, scores = self.filterOutputBoxes(self.boxes, self.scores, preNmsCount=preNmsCount, nmsThreshold=nmsThreshold, maxOutSize=maxOutSize)
  File "/home/username/RFCN-tensorflow/BoxEngine/RPN.py", line 221, in filterOutputBoxes
    scores, boxes = tf.cond(tf.shape(scores)[0] > preNmsCount , lambda: tf.tuple(MultiGather.gatherTopK(scores, preNmsCount, [boxes])), lambda: tf.tuple([scores, boxes]))
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/ops/control_flow_ops.py", line 1753, in cond
    orig_res_t, res_t = context_t.BuildCondBranch(fn1)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/ops/control_flow_ops.py", line 1659, in BuildCondBranch
    original_result = fn()
  File "/home/username/RFCN-tensorflow/BoxEngine/RPN.py", line 221, in <lambda>
    scores, boxes = tf.cond(tf.shape(scores)[0] > preNmsCount , lambda: tf.tuple(MultiGather.gatherTopK(scores, preNmsCount, [boxes])), lambda: tf.tuple([scores, boxes]))
  File "/home/username/RFCN-tensorflow/Utils/MultiGather.py", line 30, in gatherTopK
    values, indices = tf.cond(isMoreThanK, lambda: tf.nn.top_k(t, k=k, sorted=sorted), lambda: tf.tuple([t, tf.zeros((0,1), tf.int32)]))
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/ops/control_flow_ops.py", line 1777, in cond
    "Incompatible return types of fn1 and fn2: {}".format(e))
TypeError: Incompatible return types of fn1 and fn2: The two structures don't have the same sequence type. First structure has type <class 'tensorflow.python.ops.gen_nn_ops.TopKV2'>, while second structure has type <type 'list'>.
```

Could you possibly suggest what could be the problem?
I am using Ubuntu 16.04, python 2.7, tensorflow 1.1.0.

**Comment by RobertCsordas** [comment]
I have 0 free time this week, but I will check it on the weekend. Sorry about the delay.

**Comment by sevaxyz** [comment]
OK. Thank you for considering the issue and staying in touch.

Here's the changes I applied to the code: [RFCN-tensorflow.patch](https://gist.github.com/kazarey/ff9c84c03fc0ea3f2ac4164a7ed66895). The problem seems to be just with Python 2.7, because `./test.py` worked fine with Python 3.

**Comment by RobertCsordas** [comment]
Sorry for the delay. I updated the makefile to include flags for turning off GPU support and EABI fallback. Now you should be able to build the project with "USE_OLD_EABI=0 USE_GPU=0 make" command, without any patches.

However I cannot reproduce the original error. I tried it on Arch with Python 2.7.13 and 3.6.1. Both has TF 1.1.0 installed (with pip). I also tried your patch, and the effects are the same: it works. However the need for USE_OLD_EABI=0 is a sign that you are using a self-built TF. Maybe it is a later, master branch version, which is newer than 1.1? Some APIs may be changed, or the master might be even unstable (although this is very unlikely). Can you please install the official version (pip install tensorflow) and try it with that version?

**Comment by sevaxyz** [comment]
Sorry for the confusion - I indeed built tensorflow from source code. Installing it through `pip install tensorflow` solved the issue for Python 2. Guess it really was some API incompatibility issue then. Thank you for the help.

And thank you for adding the GPU flag to the Makefile.
